data:extend({
	{
		type = "bool-setting",
		name = "disable burner inserters",
		setting_type = "startup",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "disable solid fuel from heavy oil",
		setting_type = "startup",
		default_value = true,
	},
	{
		type = "double-setting",
		name = "solar panel power output (kW)",
		setting_type = "startup",
		default_value = 6,
	},
	{
		type = "double-setting",
		name = "accumulator max energy (MJ)",
		setting_type = "startup",
		default_value = 500,
	},
	{
		type = "double-setting",
		name = "solar panel cost multiplier",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "double-setting",
		name = "accumulator cost multiplier",
		setting_type = "startup",
		default_value = 10,
	},
	{
		type = "double-setting",
		name = "boiler cost multiplier",
		setting_type = "startup",
		default_value = 10,
	},
	{
		type = "double-setting",
		name = "steam engine cost multiplier",
		setting_type = "startup",
		default_value = 0.5,
	},
	{
		type = "double-setting",
		name = "fast inserter power cost (KJ)",
		setting_type = "startup",
		default_value = 4.5,
	},
	{
		type = "double-setting",
		name = "fast inserter cost multiplier",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "double-setting",
		name = "fast inserter idle power (kW)",
		setting_type = "startup",
		default_value = 0.8,
	},
	{
		type = "double-setting",
		name = "solid fuel energy (MJ)",
		setting_type = "startup",
		default_value = 20,
	},
	{
		type = "double-setting",
		name = "rocket fuel energy (MJ)",
		setting_type = "startup",
		default_value = 200,
	},
	{
		type = "double-setting",
		name = "rocket fuel crafting time",
		setting_type = "startup",
		default_value = 120,
	},
	{
		type = "double-setting",
		name = "lab power use (kW)",
		setting_type = "startup",
		default_value = 120,
	},
	{
		type = "double-setting",
		name = "energy shield mk2 recharge rate",
		setting_type = "startup",
		default_value = 24,
	},
	{
		type = "double-setting",
		name = "fish healing",
		setting_type = "startup",
		default_value = 20,
	},
	{
		type = "double-setting",
		name = "personal laser defense damage multiplier (base game is 3)",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "double-setting",
		name = "personal laser defense power use (KJ)",
		setting_type = "startup",
		default_value = 75,
	},
	{
		type = "double-setting",
		name = "assembling machine 1 cost multiplier",
		setting_type = "startup",
		default_value = 1,
	},
	{
		type = "double-setting",
		name = "assembling machine 1 energy usage (kW)",
		setting_type = "startup",
		default_value = 75,
	},
	{
		type = "double-setting",
		name = "assembling machine 1 crafting speed",
		setting_type = "startup",
		default_value = 0.5,
	},
	{
		type = "double-setting",
		name = "assembling machine 1 pollution",
		setting_type = "startup",
		default_value = 4,
	},
	{
		type = "double-setting",
		name = "assembling machine 2 cost multiplier",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "double-setting",
		name = "assembling machine 2 energy usage (kW)",
		setting_type = "startup",
		default_value = 200,
	},
	{
		type = "double-setting",
		name = "assembling machine 2 crafting speed",
		setting_type = "startup",
		default_value = 1,
	},
	{
		type = "double-setting",
		name = "assembling machine 2 pollution",
		setting_type = "startup",
		default_value = 6,
	},
	{
		type = "double-setting",
		name = "assembling machine 3 cost multiplier",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "double-setting",
		name = "assembling machine 3 energy usage (kW)",
		setting_type = "startup",
		default_value = 1600,
	},
	{
		type = "double-setting",
		name = "assembling machine 3 crafting speed",
		setting_type = "startup",
		default_value = 4,
	},
	{
		type = "double-setting",
		name = "assembling machine 3 pollution",
		setting_type = "startup",
		default_value = 18,
	},
	{
		type = "double-setting",
		name = "stone furnace cost multiplier",
		setting_type = "startup",
		default_value = 1,
	},
	{
		type = "double-setting",
		name = "stone furnace energy usage (kW)",
		setting_type = "startup",
		default_value = 90,
	},
	{
		type = "double-setting",
		name = "stone furnace crafting speed",
		setting_type = "startup",
		default_value = 1,
	},
	{
		type = "double-setting",
		name = "stone furnace pollution",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "int-setting",
		name = "stone furnace module slots",
		setting_type = "startup",
		default_value = 0,
	},
	{
		type = "double-setting",
		name = "steel furnace cost multiplier",
		setting_type = "startup",
		default_value = 1,
	},
	{
		type = "double-setting",
		name = "steel furnace energy usage (kW)",
		setting_type = "startup",
		default_value = 135,
	},
	{
		type = "double-setting",
		name = "steel furnace crafting speed",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "double-setting",
		name = "steel furnace pollution",
		setting_type = "startup",
		default_value = 3,
	},
	{
		type = "int-setting",
		name = "steel furnace module slots",
		setting_type = "startup",
		default_value = 1,
	},
	{
		type = "double-setting",
		name = "electric furnace cost multiplier",
		setting_type = "startup",
		default_value = 2,
	},
	{
		type = "double-setting",
		name = "electric furnace energy usage (kW)",
		setting_type = "startup",
		default_value = 350,
	},
	{
		type = "double-setting",
		name = "electric furnace crafting speed",
		setting_type = "startup",
		default_value = 4,
	},
	{
		type = "double-setting",
		name = "electric furnace pollution",
		setting_type = "startup",
		default_value = 2.5,
	},
	{
		type = "int-setting",
		name = "electric furnace module slots",
		setting_type = "startup",
		default_value = 3,
	},
})
